rules/license-detectable-by-licensee.js
licensee does not work on Linux, isWindows is a function, see https://www.npmjs.com/package/is-windows
=> fix(licensee): isWindows is a function

rules/file-contents.js, rulesets/default.json
To avoid false-negatives when the README.md references the LICENSE file,
make the readme-references-license rule case-insensitive.
To do so, support passing RegExp flags via the options.
=> Make readme-references-license case-insensitive

README.md
In running repolinter I noticed that you need to install log-symbols before you can run it and it's not mentioned in the README.
=> Update README to mention log-symbols installation

rules/license-detectable-by-licensee.js
At least with licensee 9.2.1 there is no leading '\n' anymore. Fix the
regex to match in any case.
=> Fix the regex to match the license reported by licensee

rules/git-grep-commits.js, rules/git-grep-log.js, rules/git-list-tree.js, rules/git-working-tree.js, rulesets/git.json
The git ruleset contains two new rules that search the commit messages
and the commits themselves for configurable blacklisted words. These
words can in fact be extended regular expressions. This is a new ruleset
instead of adding the rules to the default ruleset as these checks can be
a bit time consuming, depending on the size of the Git history.
=> Add a new ruleset with Git-related checks

README.md, index.js
It may be more convenient to name the config file exactly like the tool,
so allow also "repolinter.json" as a name.
=> Allow the config file to be named repolinter.json as a fallback

.eslintrc, .gitignore, README.md, bin/repolinter.js, formatters/json_formatter.js, formatters/symbol_formatter.js, index.js, package-lock.json, package.json, tests/formatters/json_formatter_tests.js, tests/formatters/symbol_formatter_tests.js, tests/package/repolinter.json, tests/package/repolinter_tests.js
I've [started working on](https://github.com/jwsloan/codeclimate-repolinter) a [CodeClimate](https://codeclimate.com/) [Engine](https://docs.codeclimate.com/docs/building-a-code-climate-engine) that uses `repolinter`. To complete it, I need to have the output adhere to Code Climate's [issue](https://github.com/codeclimate/spec/blob/master/SPEC.md#issues) spec.
This change will allow me (or anyone else) to do that, and also allow JSON output as request in issue #43.
=> Allow for custom results formatters

.vscode/launch.json, README.md, formatters/json_formatter.js, formatters/symbol_formatter.js, index.js, lib/result.js, package-lock.json, rules/directory-existence.js, rules/file-contents.js, rules/file-existence.js, rules/file-starts-with.js, rules/file-type-exclusion.js, rules/git-grep-commits.js, rules/git-grep-log.js, rules/git-list-tree.js, rules/git-working-tree.js, rules/license-detectable-by-licensee.js, tests/formatters/json_formatter_tests.js, tests/formatters/symbol_formatter_tests.js, tests/rules/file_contents_tests.js, tests/rules/file_existence_tests.js, tests/rules/file_starts_with_tests.js, tests/rules/file_type_exclusion_tests.js, tests/rules/git_grep_commits_tests.js, tests/rules/git_grep_log_tests.js, tests/rules/git_list_tree_tests.js, tests/rules/git_working_tree_tests.js
This change is another step toward getting a codeclimate-repolinter engine created. The addition of a `Result` class allows a formatter to have the additional information needed. 
- The Result class exposes:
- The rule itself
- The message returned by running the rule
- The target file/directory/commit the rule was run against
- The status of the result (success,error,warning)
Once I finished this, I realized the word `rule` is overloaded some in the code. I'm open to suggestions on how to fix that. Either in this PR, or in a separate one. Of course, I'm open to any other suggestions as well. I realize this is a rather large change.
/cc @caniszczyk, @bufferoverflow
=> Refactor the rules to return a new Result class

rules/file-not-contents.js, tests/rules/file_not_contents_tests.js
Fixes #58. Apologies for the c+p of file-contents. Feels like #21 would be needed to stop the c+p.
=> Adding a rule that fails if contents are found in a file

rulesets/default.json
The http://reuse.software/ initiative driven by fsfe provides best practices for license headers and SPDX usage. Some of those best practices are also adopted within Linux Kernel. This change modifies the  license-headers-exist rule so that projects following the reuse.software guidelines do pass when executing repolinter, see https://git.fsfe.org/reuse/simple-hello/src/branch/master/src/server.js as an example.
=> fix: make license-headers-exist reuse.software compatible

README.md, rulesets/default.json
* Update the default ruleset for CI check for a Jenkins declarative pipeline file (`Jenkinsfile`)
* `README.md` updates (see commit for details) to clarify the rules, and a few minor typos, link fixes, and formatting.
The project is great & really useful.  Thanks!
=> Update default ruleset (Jenkins) and README 

rulesets/default.json
`setup.py` is the standard Python setuptools packaging file. It will
likely exist more often than `requirements.txt` (which specifies the
project's package dependencies) because the latter might not exist if
the project has no dependencies.
=> Recognize setup.py as Python package metadata

rulesets/default.json
`Cartfile` is used by the [Carthage](https://github.com/Carthage/Carthage) dependency manager.
`Podfile` and `*.podspec` are used by the [CocoaPods](https://cocoapods.org/) dependency manager.
`Package.swift` is used by the [Swift Package Manager](https://swift.org/package-manager/).
=> Add objective-c and swift package metadata file patterns

axioms/licensee.js, axioms/linguist.js, index.js, lib/licensee.js, rulesets/default.json
It breaks one of the tests; not sure why the test is testing this.
1) rule git_grep_commits fails if the blacklist pattern matches a commit:
AssertionError: expected '(axioms/licensee.js) contains blacklisted words in commit 7a7f9d7.\n\tBlacklist: Copyright 2017 TODO Group\\. All rights reserved\\.' to match /\(bin\/repolinter\.js\) contains blacklisted words in commit \w{7}, and \d+ more commits\./
at Context.it (tests/rules/git_grep_commits_tests.js:48:36)
=> Adding Axioms - migrating linguist/adding licensee

rules/file-starts-with.js, rulesets/default.json
I was testing on a few of our projects and noticed `source-license-headers-exist` failures because in our headers we use "LICENSE" vs. "License". This PR is to make the `file-starts-with` rule optionally case insensitive for the patterns passed in.
Test:
```
$ bin/repolinter.js --git https://github.com/facebook/docusaurus
```
Previously this had errors like:
```
⚠ source-license-headers-exist: The first 5 lines of 'website/pages/en/help.js' do not contain the patterns:
License
```
Now this passes:
```
✔ source-license-headers-exist: The first 5 lines of 'website/pages/en/help.js' contain all of the requested patterns.
```
=> Add option to ignore case for file-starts-with rule

README.md, rules/file-contents.js, rulesets/default.json, tests/rules/file_contents_tests.js, tests/rules/git_grep_commits_tests.js
This ensures there is an email address in the code of conduct file.
This also extends the file-contents functionality to have a
human-readable contents for those cases where the contents you are
searching for is not human-readable, like a regexp.
Updated README to reflect the changes.
Fixed an overly-strict git grep commits test.
=> PR#29: Check Code of Conduct for Email Address

NOTICE, README.md, rules/file-existence.js, rulesets/default.json, tests/rules/file_existence_tests.js
This also extends the file-exists rule to have a fail-message to further
explain why a file should be there.
=> PR#65: Adding NOTICE file

README.md, lib/file_system.js, rules/file-existence.js, rulesets/default.json, tests/lib/file_system_tests.js, tests/rules/file_existence_tests.js
This allows an option to be passed into the file-exists and
directory-exists  rules to allow for case-insensitive searches.
This also makes the test directory deeply embedable by default.
README updated with the changes and tests added.
=> Fixing PR #67: Add nocase option for files & dirs

README.md
With npx, we can now run repolinter without checking out the code as
long as npm >= 5.2.0 is installed, or npx itself is installed (for
earlier versions of npm.
=> PR #25: Added npx details to README

rulesets/default.json
According to [Circle CI docs](https://circleci.com/docs/2.0/#adding-a-yml-file), the config file for v2.0 is in a different place. This PR aims to add this check.
Test:
```
bin/repolinter.js --git https://github.com/facebook/Docusaurus
```
Before the change, this resulted in:
```
...
✔ license-detectable-by-licensee: Licensee identified the license for project: MIT License
✔ test-directory-exists: found (admin/testing-changes-on-Docusaurus-itself.md)
✖ integrates-with-ci: not found: (.gitlab-ci.yml, .travis.yml, appveyor.yml, circle.yml, Jenkinsfile)
...
```
After the change, I see:
```
...
✔ license-detectable-by-licensee: Licensee identified the license for project: MIT License
✔ test-directory-exists: found (admin/testing-changes-on-Docusaurus-itself.md)
✔ integrates-with-ci: found …
```
=> Add CI check for Circle CI 2.0 config file

Gemfile, lib/licensee.js, rules/license-detectable-by-licensee.js
As of version 9.9.0 licensee's command line usage has changed and
requires a sub-command to be specified. See
https://github.com/benbalter/licensee/releases/tag/v9.9.0
=> licensee: Use the "detect" sub-command

bin/repolinter.js, index.js, rules/git-grep-commits.js, rules/git-list-tree.js, tests/rules/file_contents_tests.js, tests/rules/file_existence_tests.js, tests/rules/file_not_contents_tests.js, tests/rules/file_starts_with_tests.js, tests/rules/file_type_exclusion_tests.js, tests/rules/git_grep_commits_tests.js, tests/rules/git_grep_log_tests.js, tests/rules/git_list_tree_tests.js
The main motive of doing this is to have a freedom of using repolinter as dependency. Adding a return statement is more easy than using node's child process to monitor stdout and parse it again.
=> returning scan result as an object and adding ruleset to the signature of lint function.

package-lock.json, package.json
- chai, chai-string: moved to devDependencies
- fs: dropped (ships with node)
- npm: dropped (unused)
- path: dropped (ships with node)
This substantially decreases the install size from 93 MB to 1.4 MB when used as a dependency or via `npx`.
=> Drop unused dependencies, move some to dev

index.js, rulesets/default.json
This, via a ruleset change, stops an error when licensee is not installed as it'll only run if the axiom succeeds. Also fixing a bug in the SPDX code in the default as that was not the correct SPDX for Apache
=> Adding wildcards to axioms (#100). 

ISSUE_TEMPLATE, PULL_REQUEST_TEMPLATE, README.md, rulesets/default.json
Refer to issue #83 
Check if recommended templates exists in the root directory or under `.github`. The templates are `ISSUE_TEMPLATE*` and `PULL_REQUEST_TEMPLATE*`.
I tested locally and saw the failure messages first:
```
✖ github-issue-template-exists: not found: (ISSUE_TEMPLATE*, .github/ISSUE_TEMPLATE*)
✖ github-pull-request-template-exists: not found: (PULL_REQUEST_TEMPLATE*, .github/PULL_REQUEST_TEMPLATE*)
```
I then added sample template files and saw the successes. I tested adding the files in the root and under `.github`.
```
✔ github-issue-template-exists: found (ISSUE_TEMPLATE)
✔ github-pull-request-template-exists: found (.github/PULL_REQUEST_TEMPLATE)
```
=> Add a rule for issue and pull request templates

rulesets/default.json
AppVeyor alternatively supports configuration file names with a leading dot, see
https://www.appveyor.com/docs/build-configuration/#yaml-file-alternative-naming
=> Add alternative AppVeyor configuration file name

rules/file-contents.js, tests/rules/file_contents_tests.js
The file content module does not return a Result object if no files exist. This patch makes the module return a failing Result object in that case if they use a 'fail-on-non-existent' flag in the options.
=> Add support for non-existent files to file-contents module

rules/file-contents.js, tests/rules/file_contents_tests.js
I introduced a bug into repo linter in one of my previous commits
Basically, targets passed into Result objects are typically null
(https://github.com/todogroup/repolinter/blob/f11d2aaa4eb70c3f194e6c5a805de0a42ca08694/index.js#L80) or
a string. I passed in an array which is atypical. This patch instead
passes in null as the target because it matches nothing.
$ node_modules/mocha/bin/mocha tests/rules/file_contents_tests.js
=> Make file-contents rule target more consistent

lib/file_system.js, rules/file-starts-with.js, tests/rules/file_starts_with_tests.js
Fixing a bug in the `file-contents` module. Globbing patterns would include
directories. When we'd iterate over them, the code would try to open them and
'read their contents'. Being a directory, this would throw.
=> Make file-contents module only handle files

README.md, lib/file_system.js, package-lock.json, package.json, rules/file-starts-with.js, tests/rules/file_starts_with_tests.js
A lot of repos include static assets (for example, facebook/react-native ships with .png's). This
patch should filter out many of them
=> Creating option to skip binary files on file-starts-with rule

README.md, lib/file_system.js, rules/file-not-contents.js, rules/file-starts-with.js, tests/rules/file_not_contents_tests.js, tests/rules/file_starts_with_tests.js
1) This change, like #113, makes the rule only apply to files (instead of
including directories
2) Add an option to return a success if no file is found matching the target
Note:
This PR contains the contents from #113
=> Make file_not_contents rule return a success if no files are found

README.md
* README.md was not properly referencing to anchor for source-license-headers-exist section
* Fixed link by removing superfluous [ character
Fixing source-license-headers-exist link in documentation which currently results in a 404
* Fixed link by removing superfluous [ character
* Click on source-license-headers-exist link from rendered README.md and check whether the link now works
=> Fixed link to source-license-headers-exist

README.md, lib/file_system.js, package.json, rules/file-starts-with.js, tests/lib/file_system_tests.js, tests/lib/symlink_for_test, tests/rules/file_starts_with_tests.js
Kinda a grab bag of things: See commit descriptions for details.
Adding succeed-on-non-existent to file-starts-rule
Add `npm fix` command for simple standard js linter fixes
Ignoring paths and extensions for `file-starts-with` module
=> Many changes

lib/file_system.js, tests/lib/file_system_tests.js, tests/lib/symlink_for_test
This was making the file not contents module fail because a path was
being returned (the symlink) but opening it to read the symlink's
contents would return undefined
=> [oss] Making findAllFiles ignore symlinks for **

rulesets/default.json
Would like to add check for Drone CI/CD into default ruleset.
This only changes rulesets/default/json
no code changes
=> This adds .drone.yml to integrates-with-ci default rulesets

package.json
Now, we can do `yarn test` without getting `'describe' is not defined.` errors
=> adding standard env variable to deal with mocha

lib/file_system.js, rules/file-contents.js, rules/file-not-contents.js, rules/file-starts-with.js, tests/rules/broken_symlink_for_test, tests/rules/file_contents_tests.js, tests/rules/file_not_contents_tests.js, tests/rules/file_starts_with_tests.js
https://github.com/isaacs/node-glob/issues/170 made it so that globs that match
broken symlinks are returned as file paths. This patch works around that issue
by catching exceptions thrown when opening files.
I opted to handle exceptions instead of filtering out broken symlinks in
fs.getAllFiles() because of the comment here: https://nodejs.org/api/fs.html#fs_fs_stat_path_options_callback
I changed the file content getters to return undefined explicitly when no file
content is returned. This is to be consistent with what's already there.
=> Dealing with broken symlinks

lib/linguist.js
The linguist command was renamed from `linguist` to `github-linguist` in https://github.com/github/linguist/pull/4208.
This updates linguist support to attempt to run both commands, returning the first one that succeeds.
There do not appear to be tests for the current linguist support. I've tested it locally that this works with the latest version of linguist.
=> Fix linguist since command has been renamed

rulesets/default.json
Adding support for root, `.github`, and `docs` as a location for support
contributing, and code of conducts files. GitHub supports these
See
https://help.github.com/articles/setting-guidelines-for-repository-contributors/
https://help.github.com/articles/adding-support-resources-to-your-project/
https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/
=> adding directories in which to find CONTRIBUTING, SUPPORT and COC files

Dockerfile, lib/linguist.js
Between Licensee and Linguist, there are a lot of dependencies needed to get `repolinter` working to its fullest potential.
This PR adds a `Dockerfile` which builds both the Ruby and Node dependencies.
Usage:
```
$ docker run -it -v $PWD:/src -w /src bkeepers/repolinter
Target directory: /src
Ruleset: repolint.json
Linguist Axiom: Linguist not found in path, only running language-independent rules
✔ license-file-exists: found (LICENSE)
✔ readme-file-exists: found (README.md)
✔ contributing-file-exists: found (CONTRIBUTING.md)
✔ code-of-conduct-file-exists: found (CODE_OF_CONDUCT.md)
✔ readme-references-license: File README.md contains license
✔ binaries-not-present: Excluded file type doesn't exist (**/*.exe,**/*.dll,!node_modules/**)
✔ test-directory-exists: found (script/test)
✔ …
```
=> Add Dockerfile to support running in a container

rulesets/default.json
These are two major CI platforms that are not currently recognized by repolinter.
Manually ran repolinter on a repository that has GitHub Actions configured.
=> Support GH Actions and Azure in the default integrates-with-ci rule

lib/linguist.js
repolinter couldn't find github-linguist despite github-linguist being installed...because Windows.
Use the `isWindows()` method from the (working) licensee finding code to make this work on Windows.
Run repolinter without the patch and note the `Linguist Axiom: Linguist not found in path, only running language-independent rules` message in the results. Check that Linguist was indeed installed (I used `gem list | grep linguist` in Git Bash on Windows 10).
Now add the patch, rerun repolinter, rejoice because the error is gone...and the notable lag time means github-linguist is doing its job. 😉
=> Fix github-linguist finding on Windows

README.md, rules/file-hash.js, tests/rules/file_hash_tests.js
Add a rule that checks to see if a file matches a hash.
This is useful for projects that specify exact files, such as the Apache
license, in a specific place with specific content.  Much better than
making a giant glob out of the contents.
Signed-off-by: Danno Ferrin <danno.ferrin@gmail.com>
Allow entire static file contents to be checked efficiently.  Globs can be used but are quite obtuse when we enter the multi-kilobyte range.
Add a `file-hash` rule.  Options are `file`, `hash`, `algorithm`, and `succeed-on-non-existent`.  
`file` and `hash` have no default, that is required for each rule.  `file` is like other uses. `hash` is the hex representation of the hash. 
`algorithm` defaults to `sha256`.  The hash algorithm to use.  Any node crypto value can be used.
`succeeds-on-non-existent` …
=> Add file-hash rule

rulesets/default.json
The GitHub guidelines specify that some files can be located inany of the following places:
- the root of the repository
- the .github folder
- the docs folder
See: https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file
However, current rules only support this partially.
Closes #89
Add all paths to all supported files.
I used these settings locally.
=> Support docs and .github folders

package-lock.json, package.json
Signed-off-by: Matthew B White <whitemat@uk.ibm.com>
Hyperledger are using repolinter
Added is-windows as an explicit dependency
To reproduce and test. 
- clone the repo, and `npm install --production`
- `npm link`
- `repolinter .`
this will fail, as `linguist.js` pulls in `is-windows` but it's not a production dependency.
Repeat the above with the additional dependency and all works as expected
=> issue#163 is-windows

Dockerfile
I tried running the commands documented in the comments here and found it didn't work.
Just the addition of the -w parmeter on the non-git launch.  Otherwise it tries running in /app and gives results for repolinter.
n/a
=> Updated the Dockerfile comment to make non git runs work

axioms/contributor-count.js, index.js, package-lock.json, package.json, tests/axioms/contributor_count_test.js, tests/package/repolinter.json
See issue #169 
Adds axiom to enable rules only on projects with a certain amount of contributors. Uses the [node-gitlog](https://github.com/domharrington/node-gitlog) library to get the contributor count of the repository by looking at the commit authors. This result can be a bit higher than the actual contributor count in some cases, as some authors could be bots or use different names in their commits but it seems to be quite accurate.
The axiom can be included and used like any other axiom, but it also supports the greater than or lesser than symbols. See [tests/package/repolint.json](https://github.com/nokia/repolinter/blob/a890f8ab11c86daa2d303a04c97af888dd8a1498/tests/package/repolinter.json#L10) for an example. 
Some tests are included in `tests/axioms/contributor_count_test.js`.
=> Add contributor-count axiom

.github/settings.yml
Add a simple settings.yml to track settings and maintainer access.
=> Add settings.yml to list maintainers

axioms/licensee.js, axioms/linguist.js, lib/command_exists.js, lib/licensee.js, lib/linguist.js, package-lock.json, package.json, tests/axioms/licensee_tests.js, tests/axioms/linguist_tests.js
This PR moves the axioms to async calls, and switches to the [command-exists](https://www.npmjs.com/package/command-exists) library for verification of the installation of licensee and linguist. This change was made because I encountered some stability issues when testing with linguist/licensee on MacOS, and this change seemed to resolve the issue.
=> fix: convert axioms to async calls

rulesets/default.json
Signed-off-by: John Mertic <jmertic@linuxfoundation.org>
GitHub will create a ISSUE_TEMPLATE or PULL_REQUEST_TEMPLATE folder if the project has multiple templates
Add ` "dirs": true` to the `github-issue-template-exists` and `github-pull-request-template-exists` to check for that folder
Ran against my project at https://github.com/lf-energy/tsc-template/actions?query=workflow%3A%22Weekly+Lint+repository%22
=> Add  "dirs": true to check for multiple pull request and issue templates

rules/file-hash.js, tests/rules/file_hash_tests.js
This PR fixes a typo preventing the `fileHash` rule from being configured using the legacy format (`files` instead of `globsAny`).
=> fix: file-hash now accepts legacy configuration format

.github/workflows/build.yaml, .github/workflows/docs.yaml
Updates the Github Actions CI process to reflect the recent depreciation of the `set-env` command.
=> ci: update workflow files

.github/workflows/ci.yaml, .releaserc.json, README.md, package.json
This PR builds on #196, but adds semantic-release to ensure that version tags are consistently updated for NPM, GitHub, and GHCR. A PAT of a user with package scopes in a `GHCR_PAT` secret and an NPM token in in a `NPM_TOKEN` secret  is required in order for this PR to work properly.
=> ci: switch to semantic-release and add docker publish

docs/rules.md, rules/file-contents-config.json, rules/file-not-contents-config.json
👋Hi there!
I was working on a new ruleset that we can use at Philips and noticed a small issue in the documentation regarding the _fail-on-non-existent_ option.  
Change all inconsistencies regarding the fail-on-non-existent option in the docs and configs.
Test if documentation still compiles.
=> docs: fail-on-non-exist should be fail-on-non-existent

.github/workflows/ci.yaml
This PR updates the short SHA of one of the actions to a versioned tag now that it exists. Actions no longer supports the short SHA for a named Action, as such post-merge CI is failing as it cannot checkout the Action.
This change also migrates from the custom PAT_TOKEN to the GITHUB_TOKEN now that the GHCR supports the GITHUB_TOKEN for push event authentication to the registry: https://github.blog/changelog/2021-03-24-packages-container-registry-now-supports-github_token/
=> Update Docker Publishing

.github/workflows/ci.yaml, .github/workflows/docs.yaml
This PR updates the CI package versions used by the repolinter GH Actions pipeline.
=> ci: bump CI package versions

.github/workflows/ci.yaml
This PR _should_ fix a bug with ruby gems in the CI pipline that is causing MacOS builds to fail.
=> ci: switch to setup-ruby for installing bundle gems

README.md, bin/repolinter.js, index.js, lib/config.js, rulesets/schema.json, tests/lib/absolute-override.yaml, tests/lib/config_tests.js, tests/lib/default.json, tests/lib/loop-a.yaml, tests/lib/loop-b.yaml, tests/lib/loop-self.yaml, tests/lib/repolinter.yaml
This adds support for inheriting rulesets with a new `extends` property:
```yaml
"$schema": "https://raw.githubusercontent.com/todogroup/repolinter/master/rulesets/schema.json"
version: 2
extends: "https://raw.githubusercontent.com/todogroup/repolinter/master/rulesets/default.json"
rules:
license-file-exists:
level: off
```
The full parsed config files are merged using [`lodash.merge`](https://lodash.com/docs/4.17.15#merge), with the "current" file overwriting the "extended" file.  This allows adding new rules, disabling rules by setting `level: off`, or customizing options for a rule (though the way lodash merges values may not always be what you expect... it requires a little experimenting).
This PR contains two commits... the first just refactors the existing config loading logic, …
=> add support for inheriting rulesets

.github/workflows/repolinter.yaml
for now, we're just using the default ruleset, since it covers the most common things, and it already passes.  We can certainly customize that down the road with other rules.  
If and when we do use a custom ruleset file, we're probably want to put it in the `.github` directory.  Even though it's common to have a `repolinter.json` file in the root of the project, because this is for the repolinter project itself, I think that might cause some issues with some new tests that are being added in a separate PR.  But none of that actually matters right now.
(relates to todogroup/work-day-activities#8)
=> run repolinter on repolinter using repolinter-action

Dockerfile
This PR updates the Dockerfile to resolve the CI errors seen in #223. In addition to testing Repolinter, I've tested this Dockerfile against [repolinter-action](https://github.com/todogroup/repolinter-action) and it [appears to work the same](https://github.com/todogroup/repolinter-action/runs/3709441168?check_suite_focus=true). I've also pushed a [test container](https://github.com/users/prototypicalpro/packages/container/package/repolinter) available at  `ghcr.io/prototypicalpro/repolinter:test` if that is useful.
=> Update Dockerfile to fix build error

.github/repolinter.yaml, .github/workflows/repolinter.yaml
- switch to todogroup/repolinter-action
- use todogroup default repolinter ruleset
relates to todogroup/work-day-activities#8
=> update repolinter github action

docs/rules.md, rules/best-practices-badge-present-config.json, rules/best-practices-badge-present.js, rules/rules.js, rulesets/default.json, rulesets/schema.json, tests/rules/best_practices_badge_tests.js
Check Best Practices Badge is present in the README and optionally check the badge meets a desired level (passing, silver, gold, ...)
The rule is off by default to avoid breaking any repos using repolinter. 
Add `best-practices-badge-present` rule, which will check there is a URL that looks like `https://bestpractices.coreinfrastructure.org/projects/$id` in the readme. The rule won't actually check that the badge has the right markdown, which would require to convert the markdown to html and then parse the html, but I think this solution is good enough.
Additionally, if the option `minPercentage` is passed as an option to the rule, the Best Practices Badge API will be queried with the URL found in the readme and we will assert that the `tiered_percentage` returned by the API is greater or …
=> Check Best Practices Badge present in README and optionally badge level

docs/axioms.md
The link to `axioms/packagers.md` in `docs/axioms.md` is broken
Point to right location of the file
=> Fix broken link in axioms.md

formatters/markdown_formatter.js, package-lock.json, package.json
- update markdown formatter feature to fix [MD051](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md051)
Update dependencies
Update version of `markdownlint` to latest@0.26.0
Update formatter so markdown output are compliant to MD051.
=> patch: udpate markdownlint@0.26.0

README.md, axioms/axioms.js, fixes/file-create.js, fixes/file-modify.js, fixes/file-remove.js, fixes/fixes.js, index.js, lib/command_exists.js, lib/config.js, lib/github_markup.js, lib/licensee.js, lib/linguist.js, package-lock.json, package.json, rules/file-contents.js, rules/file-existence.js, rules/file-hashes-not-exist.js, rules/file-no-broken-links.js, rules/file-not-contents.js, rules/file-not-exists.js, rules/file-starts-with.js, rules/file-type-exclusion.js, rules/git-grep-commits.js, rules/git-grep-log.js, rules/git-list-tree.js, rules/git-working-tree.js, rules/json-schema-passes.js, rules/large-file.js, rules/license-detectable-by-licensee.js, rules/rules.js
* upgrade *documentation* version to 14.0.0 based on dependabot commit.
* fix the rest to make apidoc generation works.
* prepare for other dependabot PR merges, up supported nodejs version
All changes are tested:
* passed `npm run test` 
* manually verified the `npm run apidoc` generate same doc as documentation 13.2.5 version.
=> Documentation 14.0.0

.github/workflows/ci.yaml, .github/workflows/docs.yaml, tests/rules/git_grep_commits_tests.js
Update to supported versions of node.
Currently node 14, 16 and 18 are stable. See https://github.com/nodejs/release#release-schedule
Also added v19.6.1, because we're using `node:buster` in the `Dockerfile` which uses v19.6.1.
This PR will:
- remove node 10 and 12 in CI
- add node (14), 16, 18, 19 in CI
Ran tests ( `npm ci`, `npm test`, `npm apidoc` ) on macOs for:
- node v14.21.3
- node v16.19.1
- node v18.14.1
- node v19.6.1
closes: #270
=> Update versions of node in ci. Fixes ci.

Dockerfile
Currently the docker build is failing because of the usage of `node:buster` instead of `node:bullseye`. When installing `ruby` this defaults to an incompatible version.
Switch to `node:bullseye`. When installing ruby it defaults to ruby 2.7, which is fine for us.
Build the docker image locally.
```bash
$docker build -t repolinter .
```
Tested the docker image locally.
```bash
$docker run repolinter
```
=> Update versions of node in Dockerfile. Fixes ci.

lib/git_helper.js, package-lock.json, package.json, rules/git-grep-commits.js, rules/git-list-tree.js, tests/lib/git_helper_tests.js, tests/rules/git_grep_commits_tests.js, tests/rules/git_list_tree_tests.js
Use [SinonJs](https://sinonjs.org/) stub for the `GitAllCommits` function to speed up the tests. The tests were performing the rules on a big repository with a lot of commits, and the timeout was hit very frequently.
Now this should be resolved.
Now the tests will only check the following three commits:
| Commit sha | test-case |
| --- | --- |
| `3e66e3ec616d59f813bdb878e1146d03872a096e` | `git_grep_commits` |
| `c9e1b59c86c119a5a67389ffd13d026c6058492a` |`git_grep_commits` |
| `260f8cc14d6ecf0ff1f0162f88086143d813967a` |`git_list_tree` |
- Moved `gitAllCommits` in a Helper module.
- Add test for `gitAllCommits` to proof it still works.
- Use `gitAllCommits` in two slow tests.
- Stub results of `gitAllCommits` in tests with specific commits.
```
./node_modules/mocha/bin/mocha.js …
```
=> Selective test run for git tests

docs/rules.md
Correct the docs. I tried using the `succeed-on-non-exist` option but it wasn't working as expected. Upon looking at the code I realized the docs were incorrect.
Docs refer to option as `succeed-on-non-exist` but code expects `succeed-on-non-existent`
`succeed-on-non-existent` actually works where `succeed-on-non-exist` does nothing.
=> Correct succeed-on-non-exist option in docs

rulesets/default.json
Include GitHub [documented](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) locations for pull request templates.
Fixes: https://github.com/todogroup/repolinter/issues/321
GitHub documents other locations for a pull request template.
Update the list of pull request template locations to match the documentation.
Run the code on various repositories with additional locations.
=> feat: update github pull request template locations
