todogroup/repolinter

README.md, bin/repolinter.js, index.js, lib/file_system.js, package.json
This adds a bin to run the command.
```
$ bin/repolinter.js [path/to/dir]
```
I had to fix some of the path handling because things would break when the linter was run with anything besides `.` as an argument.
=> Add bin/repolinter.js

index.js, lib/file_system.js, package-lock.json, package.json, rules/file_starts_with.js
* It has built-in support for glob arrays
* It has built-in support for negation, home directory, etc.
=> Switch to using matched

rules/license-detectable-by-licensee.js
This improves the experience on Windows, also see issue #33.
=> Support running licensee on Windows

bin/repolinter.bat
This makes it easier to run on Windows, also see issue #33.
=> Add a batch file for better Windows support

bin/repolinter.bat, bin/repolinter.js
Please have a look at the individual commit messages for the details.
=> Fixes for cloning a Git repo via the --git command line option before scanning

package.json, rules/git-grep-commits.js, rules/git-grep-log.js, rules/git-list-tree.js, rulesets/git.json, tests/rules/file_contents_tests.js, tests/rules/file_existence_tests.js, tests/rules/file_type_exclusion_tests.js, tests/rules/git_grep_commits_tests.js, tests/rules/git_grep_log_tests.js, tests/rules/git_list_tree_tests.js, tests/rules/git_working_tree_tests.js
Please have a look at the individual commit messages for the details.
=> Allow Git rules to ignore case and add tests

index.js, lib/file_system.js, package.json, rules/directory-existence.js, rules/file-contents.js, rules/file-existence.js, rules/file-starts-with.js, rules/file-type-exclusion.js, rules/git-grep-commits.js, rules/git-grep-log.js, rules/git-list-tree.js, rules/git-working-tree.js, rules/license-detectable-by-licensee.js, tests/lib/file_system_tests.js, tests/rules/file_contents_tests.js, tests/rules/file_existence_tests.js, tests/rules/file_starts_with_tests.js, tests/rules/file_type_exclusion_tests.js, tests/rules/git_grep_commits_tests.js, tests/rules/git_grep_log_tests.js, tests/rules/git_list_tree_tests.js, tests/rules/git_working_tree_tests.js
As the individual commit messages state, this adds some additional features that continue to bring me closer to being able to submit a new engine to codeclimate.com that runs repolinter.
There are requirements in their Engine Spec that these changes facilitate satisfying.
Also, I set the tests to use --no-timeouts, as there were many timing out regularly on my system. Feel free to tell me to remove that.
I've included a version bump, which I'd also be happy to remove. I'm hoping you'll be able to cut a new release and push it out to npm.
/cc @caniszczyk, @bufferoverflow
=> Add additional features to support a CodeClimate Engine

README.md
Minor update to README `npx` run log due to some new additions to the repolinter.
=> Update README log output

axioms/licensee.js, axioms/linguist.js
The error handling feels pretty amateur still - I'm comparing string messages rather than subclassing Error in some way (aka still converting my Java/Ruby brain to JavaScript+Node)
=> Improving error handling and fixing bug in linguist json parsing

README.md
A previous PR of mine (#110) omitted this. See code changes for more details.
=> Updating readme with changes to file-contents rule

rulesets/default.json
Our ruleset wasn't detecting files like Code_Of_Conduct
=> Adding nocase to file checks in default rules

README.md
I'd like to help clarify install instructions and dependencies for future installers who do not have a ruby or node environment already setup. 
Lists additional prerequisites for running repolinter. This list may need to be expanded. 
Clean OS install on a non-developer environment.
=> Add unlisted command line dependencies

README.md, SECURITY.md, rulesets/default.json
https://help.github.com/en/articles/adding-a-security-policy-to-your-repository
=> Add check for security policies

package-lock.json, package.json
=> Update dependencies to latest

package-lock.json
Thanks to `npm audit fix`. ❤️ 
NPM complained about a high level vulnerability in handlebars, and recommended that `npm audit fix` would fix it. It worked this time. 😁 So I thought I'd share. 😉 
Just a version bump to handlebars (which is a 3rd level dependency, fwiw).
Same tests should pass.
=> Fix Handlebars vulnerability

.github/workflows/build.yaml
=> Add GA build matrix

.github/workflows/build.yaml
=> Fix GHA to build on PR (sigh)

rules/file-hash.js, tests/rules/file_hash_tests.js
Signed-off-by: Danno Ferrin <danno.ferrin@gmail.com>
My previous patch was breaking the linter in the tests
fix the linting errors
npm test.  make sure it passes this time.
=> lint on file-hash rule and test

package-lock.json
=> Update after an NPM audit

package-lock.json, package.json
=> Update more dependencies

axioms/licensee.js, axioms/linguist.js, axioms/packagers.js, index.js, lib/file_system.js, package-lock.json, package.json, rules/file-hash.js, rules/file-starts-with.js, rules/git-grep-commits.js, rules/git-grep-log.js, rules/git-list-tree.js, rules/git-working-tree.js, rules/license-detectable-by-licensee.js, tests/axioms/packagers_tests.js, tests/formatters/json_formatter_tests.js, tests/formatters/symbol_formatter_tests.js, tests/package/repolinter_tests.js, tests/rules/file_starts_with_tests.js
=> Update to latest dependencies

.gitignore, Gemfile.lock, package-lock.json
=> Adding lock files

.github/settings.yml
=> Add @prototypicalpro as a maintainer

formatters/markdown_formatter.js, index.js
This PR fixes a minor bug with the markdown formatter where it can display an empty list of files.
=> fix: minor updates to the markdown formatter

docs/fixes.md, fixes/file-remove-config.json, fixes/file-remove.js, fixes/fixes.js, rulesets/schema.json, tests/fixes/file_remove_tests.js
This PR adds a `file-remove` fix, which can remove a file automatically. See [the docs](https://github.com/newrelic-forks/repolinter/blob/feat/file-remove-fix-pr/docs/fixes.md#file-remove) for more information.
=> feat: add file-remove fix

docs/rules.md, rules/directory-existence.js, rules/file-existence-config.json, rules/file-not-exists-config.json, rules/file-not-exists.js, rules/rules.js, rulesets/schema.json, tests/axioms/contributor_count_test.js, tests/cli/cli_tests.js, tests/formatters/markdown_formatter_tests.js, tests/rules/file_not_exists_tests.js
This PR adds a `file-not-exists` rule. More information can be found in the [docs](https://github.com/newrelic-forks/repolinter/blob/feat/add-more-rules/docs/rules.md#file-not-exists).
=> feat: add file-not-exists rule

README.md
Fixing the file path to docs/rules.md file.
=> docs: Fix Rule Reference link to docs/rules.md

README.md
Very small fix...
This change is not important at all, and I make typos all the time, but I thought let's create this PR...
Typo in README
=> docs: Axiom instead of Axom

package-lock.json, package.json
Address #217 and #218 by removing an old developer dependency that is no longer needed.
=> chore: remove standardjs dev dep (#217, #218)

.github/settings.yml
Per conversation on Slack, proposing myself be added as a maintainer again.
=> Adding myself as a maintainer

package-lock.json, package.json
Upgrading the simple-git dependency to 3.16.0+. Resolves #278.
=> Upgrading simple-git

.releaserc.json
Semantic Release pointed to `master`
Update the configuration to `main`
=> WIP fix: semantic release update to main
